# All Rights Reserved. Copyright (c) 2021 Hitachi Solutions, Ltd.
ERROR_MESSAGE = {0: 'Internal Server Error.',
                 1: 'Request URL is incorrect.',
                 2: 'Request headers are incorrect.',
                 3: 'Request parameters are incorrect.',
                 4: 'Authentication failed.',
                 5: 'Token is invalid.',
                 6: 'Token is expired.',
                 7: 'No Permission.',
                 8: 'Request Method is incorrect.',
                 9: 'Account name is already used.',
                 10: 'Resource is already exist.',
                 11: 'Resource is not found.',
                 12: 'The requested path is invalid.',
                 13: 'The specified directory is not empty.',
                 14: 'The specified request is processing.',
                 15: 'The account is processing up to the limit.',
                 16: 'The tenant is processing up to the limit.',
                 17: 'The account name is incorrect.',
                 18: 'The new password is incorrect.',
                 19: 'Conflict with post-processing. Please try again later.',
                 20: 'Folder size exceeded the limit.',
                 }
